FROM python:3.9-slim

WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all project files to the container
COPY . .

# Expose the port Django will run on
EXPOSE 8000

# Command to run the app
CMD ["gunicorn", "wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "120"]

